### ISSUE TITLE
Observation types without namespace

### ISSUE THREAD

**Issue by nikolajkamstrup** [Kortforsyningen/FIRE-DDL#21]
Shouldn't ObservationType.ObservationType and Observation.ObservationType contain the namespace (OBS) similar to SRIDType and PunktInfoType? Even though there is only one namespace...

**Comment by kbevers** [comment]
Some time ago we decided not to bother with the `OBS:` namespace since it is the only one for observations. There are no constraints on this at the moment so it doesn't matter if the namespace is there or not.

As far as I remember there is still a ObsNamespaceValue table. It is unused at the moment but it *may* be utilized later, since there is the possibility to distinguish different types of observations via the namespace, e.g. `LVL:` for levelling and `GNSS:` for GNSS observations. In any case it should matter in the migration since the type and namespace tables are populated in the DDL and *should* be plug and play if changed in a later DDL iteration.
