### ISSUE TITLE
Rationale for event types "beregning" and "koordinat_beregnet"

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#37]
I have a hard time separating these two and the clear text explanation does not help:

* koordinat_beregnet - 'bruges når koordinater indsættes efter en beregning'
* beregning - 'bruges når nye koordinater skabes. Knytter observationer til koordinater'

If this can be made clearer it would make me happy. :)

**Comment by kbevers** [comment]
I understand the confusion, as the text basically mean the same thing. I think these were created at a time when we still hadn't decided how this should work. Ignore `beregning` for now, as `koordinat_beregnet` can be used when inserting data into both `KOORDINAT` and `BEREGNING` tables. In fact, they should always be inserted together since you can't really make a koordinat without some sort of connection to observations (and that is the purpose of `BEREGNING`). Observations can and will be inserted before they are used to create coordinates so they can't be inserted as part of the same SAGSEVENT.
